console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
terminal_background = 'p:t-background'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#24283b'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#414868'
  terminal-blue = '#7aa2f7'
  terminal-green = '#73daca'
  terminal-magenta = '#bb9af7'
  terminal-red = '#f7768e'
  terminal-white = '#c0caf5'
  terminal-yellow = '#e0af68'
  white-blue = '#a9b1d6'

[secondary_prompt]
  template = ' '
  foreground = 'p:terminal-blue'
  background = 'transparent'

[transient_prompt]
  template = ' '
  foreground = 'p:terminal-blue'
  background = 'p:t-background'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '<p:terminal-magenta>󰝰 </>'
    foreground = 'p:terminal-blue'
    background = 'transparent'
    type = 'text'

  [[blocks.segments]]
    style = 'plain'
    template = '<b>{{ .Path }}</b> <p:light-sky-blue>⚡</>'
    foreground = 'p:terminal-magenta'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    style = 'plain'
    template = '({{ .HEAD}})'
    foreground = 'p:pistachio-green'
    type = 'git'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}', '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}', '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true

  [[blocks.segments]]
    style = 'plain'
    template = ' '
    foreground = 'p:terminal-red'
    type = 'status'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }} '
    foreground = 'p:pistachio-green'
    type = 'node'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }} '
    foreground = 'p:terminal-blue'
    type = 'php'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }}'
    foreground = 'p:terminal-yellow'
    type = 'python'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full }}'
    foreground = 'p:terminal-magenta'
    type = 'julia'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Full}}'
    foreground = 'p:terminal-red'
    type = 'ruby'

  [[blocks.segments]]
    style = 'plain'
    template = 'ﳑ {{ .Full}}'
    foreground = 'p:light-sky-blue'
    type = 'go'

  [[blocks.segments]]
    style = 'plain'
    foreground = 'p:white-blue'
    type = 'command'

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'bash'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '>'
    foreground = 'p:pistachio-green'
    type = 'text'
